create table tipos_clientes (
    tipo_cliente_id number generated by default on null as identity constraint tipos_cliente_tipo_cliente_pk primary key,
    nombre varchar2(250 char),
    descripcion varchar2(250 char)
);

-- create tables
create table clientes (
  cliente_id number generated by default on null as identity Constraint clientes_cliente_id_pk primary key,
  tipo_cliente_id number,
  dpi varchar2(30 char) constraint clientes_dpi_unq unique,
  nit varchar2(30 char) Constraint clientes_nit_unq unique,
  primer_nombre varchar2(100 char) not null,
  segundo_nombre varchar2(100 char),
  tercer_nombre varchar2(100 char),
  primer_apellido varchar2(100 char) not null,
  segundo_apellido varchar2(100 char),
  apellido_casada varchar2(100 char),
  email varchar2(250 char),
  telefono varchar2(25 char),
  genero varchar2(1 char) constraint clientes_genero_ck check (
    genero in ('M','F')),
    constraint clientes_tipo_cliente_fk foreign key (tipo_cliente_id) references tipos_clientes (tipo_cliente_id) ON DELETE CASCADE
  ); 
  
  create table direcciones_cliente (
    direccion_cliente_id number generated by default on null as identity constraint direcciones_c_direccion_cli_pk primary key,
    cliente_id number,
    tipo_direccion varchar2(250 char),
    pais varchar2(250 char),
    departamento varchar2(250 char),
    municipio varchar2(250 char),
    lugar_domicilio varchar2(500 char),
    constraint fk_cliente foreign key (cliente_id) references clientes(cliente_id) ON DELETE CASCADE
);


CREATE TABLE DEPARTAMENTOS(
DEPARTAMENTO_ID number generated by default on null as identity Constraint departamentos_departamento_id_pk primary key,
NOMBRE_DEPARTAMENTO varchar2(100) NOT NULL,
PUESTO varchar2(100) NOT NULL,
UBICACION varchar2(100) NOT NULL
);

CREATE TABLE DIRECCIONES_EMPLEADO(
    DIRECCION_EMPLEADO_ID number generated by default on null as identity Constraint direcciones_empleado_direccion_empleado_id_pk primary key,
    TIPO_DIRECCION varchar2(100) NOT NULL,
    PAIS varchar2(100) DEFAULT 'Guatemala' NOT NULL,
    DEPARTAMENTO varchar2(100) NOT NULL,
    MUNICIPIO varchar2(100) NOT NULL,
    LUGAR_DOMICILIO varchar2(250) NOT NULL
);

CREATE TABLE EMPLEADOS(
    EMPLEADOS_ID number generated by default on null as identity Constraint empleados_empleado_id_pk primary key,
    DIRECCION_ID number,
    DEPARTAMENTO_ID number,
    DPI varchar2(30) constraint empleados_dpi_unq unique,
    NIT varchar2(30) constraint empleados_nit_unq unique,
    PRIMER_NOMBRE varchar2(100) NOT NULL,
    SEGUNDO_NOMBRE varchar2(100),
    TERCER_NOMBRE varchar2(100),
    PRIMER_APELLIDO varchar2(100) NOT NULL,
    SEGUNDO_APELLIDO varchar2(100),
    APELLIDO_CASADA varchar2(100),
    CORREO_ELECTRONICO varchar2(100),
    FECHA_CONTRATACION DATE NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO varchar2(10),
    CONSTRAINT fk_direccion FOREIGN KEY (Direccion_id) REFERENCES Direcciones_Empleado(Direccion_empleado_id),
    CONSTRAINT fk_departamento FOREIGN KEY (Departamento_id) REFERENCES Departamentos(Departamento_id)
);

CREATE TABLE Bancos (
    Banco_id NUMBER PRIMARY KEY,
    Codigo VARCHAR2(50),
    Nombre VARCHAR2(100),
    Tipo_Cuenta VARCHAR2(50)
);

CREATE TABLE Metodos_de_Pago (
    Metodo_Pago_id NUMBER PRIMARY KEY,
    Banco_id NUMBER,
    Nombre VARCHAR2(100),
    Descripcion VARCHAR2(255),
    CONSTRAINT fk_banco FOREIGN KEY (Banco_id) REFERENCES Bancos(Banco_id)
);

CREATE TABLE Pagos (
    Pago_id number generated by default on null as identity Constraint pagos_pago_id_pk primary key,
    Metodo_pago_id NUMBER,
    Monto_pagar NUMBER,
    Fecha_pago TIMESTAMP,
    CONSTRAINT fk_metodo_pago FOREIGN KEY (Metodo_pago_id) REFERENCES Metodos_de_Pago(Metodo_Pago_id)
);

create table facturas (
    factura_id number generated by default on null as identity constraint facturas_factura_id_pk primary key,
    cliente_id number,
    nit varchar2(30 char),
    empleado_id number,
    pago_id number,
    fecha timestamp,
    iva number(15, 4),
    subtotal number(15, 4),
    total number(15, 4),
    CONSTRAINT facturas_cliente_id_fk FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id),
    CONSTRAINT factura_nit_fk FOREIGN KEY (nit) REFERENCES clientes(nit),
    constraint factura_empleado_id_fk foreign key (empleado_id) references empleados(empleados_id),
    constraint factura_pago_id_fk foreign key (pago_id) references pagos(pago_id)
);

CREATE TABLE CUENTAS_CORRIENTES (
    CUENTA_CORRIENTE_ID number generated by default on null as identity Constraint cuentas_corrientes_cuenta_corriente_id_pk primary key,
    FACTURA_ID NUMBER NOT NULL,
    METODO_DE_PAGO_ID NUMBER NOT NULL,
    DEBE NUMBER(10, 2) NOT NULL,
    HABER NUMBER(10, 2) NOT NULL,
    SALDO NUMBER(10, 2),
    CONSTRAINT fk_cuenta_corriente_factura FOREIGN KEY (FACTURA_ID) REFERENCES Facturas(FACTURA_ID),
    CONSTRAINT fk_cuenta_corriente_metodo_pago FOREIGN KEY (METODO_DE_PAGO_ID) REFERENCES Metodos_De_Pago(METODO_PAGO_ID)
);

CREATE TABLE Devoluciones (
    Devolucion_id NUMBER PRIMARY KEY,
    Empleado_id NUMBER,
    Cliente_id NUMBER,
    Metodo_Pago_id NUMBER,
    Fecha_devolucion DATE,
    Metodo_Reembolso NUMBER,
    Monto_reembolsado NUMBER,
    CONSTRAINT fk_empleado_d FOREIGN KEY (Empleado_id) REFERENCES Empleados(Empleados_id),
    CONSTRAINT fk_cliente_d FOREIGN KEY (Cliente_id) REFERENCES Clientes(Cliente_id),
    CONSTRAINT fk_metodo_pago_d FOREIGN KEY (Metodo_Pago_id) REFERENCES Metodos_de_Pago(Metodo_Pago_id)
);

CREATE TABLE Categoria_Productos (
    Categoria_producto_id number generated by default on null as identity Constraint categoria_productos_categoria_producto_id_pk primary key,
    Nombre VARCHAR2(100),
    Descripcion VARCHAR2(255)
);

CREATE TABLE Proveedores (
    Proveedor_id number generated by default on null as identity Constraint proveedores_proveedor_id_pk primary key,
    Nombre VARCHAR2(100),
    Telefono VARCHAR2(20),
    email VARCHAR2(100),
    Descripcion VARCHAR2(255),
    Tipo_Proveedor VARCHAR2(50),
    NIT VARCHAR2(20),
    Fecha_Registro DATE,
    Estado VARCHAR2(20)
);

CREATE TABLE DIRECCIONES_PROVEEDORES(
    DIRECCIONES_PROVEEDORES_ID number PRIMARY KEY,
    TIPO_DIRECCION varchar2(100),
    PROVEEDOR_ID number,
    PAIS varchar2(100),
    DEPARTAMENTO varchar2(100),
    MUNICIPIO varchar2(100),
    LUGAR_DOMICILIO varchar2(100),
    CONSTRAINT fk_proveedor FOREIGN KEY (Proveedor_id) REFERENCES Proveedores(Proveedor_id)
);

CREATE TABLE Productos (
    Producto_id number generated by default on null as identity Constraint productos_producto_id_pk primary key,
    Proveedor_Id NUMBER,
    Categoria_producto_id NUMBER,
    Nombre VARCHAR2(100),
    Descripcion VARCHAR2(255),
    Precio_compra NUMBER,
    Precio_venta NUMBER,
    iva NUMBER,
    Marca VARCHAR2(50),
    Modelo VARCHAR2(50),
    Numero_Serie VARCHAR2(50),
    CONSTRAINT FK_Proveedor_p FOREIGN KEY (Proveedor_Id) REFERENCES Proveedores(Proveedor_Id),
    CONSTRAINT FK_Categoria_p FOREIGN KEY (Categoria_producto_id) REFERENCES Categoria_Productos(Categoria_producto_id)
);

create table factura_detalles (
    factura_detalle_id number generated by default on null as identity constraint factura_detal_factura_detal_pk primary key,
    factura_id number,
    producto_id number,
    cantidad number(15, 0),
    iva number(15, 0),
    descuento number(15, 4),
    subtotal number(15, 4),
    total number(15, 4),
    constraint fk_factura_id foreign key (factura_id) references facturas(factura_id) ON DELETE CASCADE,
    constraint fk_producto_id foreign key (producto_id) references productos(producto_id) ON DELETE CASCADE
);

CREATE TABLE Devolucion_detalles (
    Devolucion_detalle_Id number generated by default on null as identity Constraint devolucion_detalle_devolucion_detalle_id primary key,
    Devolucion_id NUMBER,
    Producto_id NUMBER,
    Cantidad NUMBER,
    Motivo VARCHAR2(255),
    Estado VARCHAR2(50),
    Descuento NUMBER,
    CONSTRAINT FK_Devolucion FOREIGN KEY (Devolucion_id) REFERENCES Devoluciones(Devolucion_id),
    CONSTRAINT FK_Producto FOREIGN KEY (Producto_id) REFERENCES Productos(Producto_id)
);

CREATE TABLE Inventarios (
    Inventario_id number generated by default on null as identity Constraint inventarios_inventario_id_pk primary key,
    Producto_Id NUMBER,
    Cantidad_inicial NUMBER,
    Cantidad_disponible NUMBER,
    Cantidad_vendida NUMBER,
    Fecha_ingreso DATE,
    Fecha_Ultima_Actualizacion DATE,
    Estado VARCHAR2(50),
    CONSTRAINT FK_Producto_i FOREIGN KEY (Producto_id) REFERENCES Productos(Producto_id)
);

CREATE TABLE Compras (
    Compra_id number generated by default on null as identity Constraint compras_compra_id_pk primary key,
    Proveedor_id NUMBER,
    Inventario_id NUMBER,
    Metodo_Pago_id NUMBER,
    Numero_factura NUMBER,
    Total NUMBER,
    CONSTRAINT FK_Proveedor_c FOREIGN KEY (Proveedor_id) REFERENCES Proveedores(Proveedor_id),
    CONSTRAINT FK_Inventario_c FOREIGN KEY (Inventario_id) REFERENCES Inventarios(Inventario_id),
    CONSTRAINT FK_Metodo_Pago_c FOREIGN KEY (Metodo_Pago_id) REFERENCES Metodos_de_Pago(Metodo_Pago_id)
);

CREATE TABLE Compras_Detalle (
    Compra_Detalle_id number generated by default on null as identity Constraint compras_detalles_compra_detalle_id_pk primary key,
    Producto_id NUMBER,
    Compra_id NUMBER,
    Cantidad NUMBER,
    Precio_Unitario NUMBER,
    Impuesto NUMBER, 
    CONSTRAINT fk_compra FOREIGN KEY (Compra_id) REFERENCES Compras(Compra_id)
);

CREATE TABLE Gastos (
    Gasto_id number generated by default on null as identity Constraint gastos_gasto_id_pk primary key,
    Metodo_Pago_id NUMBER,
    Nombre VARCHAR2(100),
    Descripcion VARCHAR2(255),
    Fecha_Gasto DATE,
    Monto NUMBER,
    CONSTRAINT fk_metodo_pago_g FOREIGN KEY (Metodo_Pago_id) REFERENCES Metodos_de_Pago(Metodo_Pago_id)
);

CREATE TABLE CUENTAS_POR_PAGAR(
    CUENTA_POR_PAGAR_ID number PRIMARY KEY,
    PROVEEDOR_ID number,
    METODO_PAGO_ID NUMBER,
    SALDO_PENDIENTE NUMBER,
    FECHA_VENCIMIENTO DATE,
    CONSTRAINT fk_proveedor_cpag FOREIGN KEY (Proveedor_id) REFERENCES Proveedores(Proveedor_id),
    CONSTRAINT fk_metodo_pago_cpag FOREIGN KEY (Metodo_pago_id) REFERENCES Metodos_de_Pago(Metodo_pago_id)
);

commit;